
model: 'centernet'
heads:
    'hm': 80
    'reg': 2
    'wh': 2

head_conv: 64

dataset: 'coco'
train_split: 'train2017'
val_split: 'val2017'
num_classes: 80

dataset_opt:
    down_ratio: 4
    flip: 0.5
    input_h: 512
    input_w: 512
    keep_res: False
    mse_loss: False
    color_aug: False
    rand_crop: True
    pad: 31
    reg_offset: True
    scale: 0.4
    shift: 0.1
    debug: False

input_shape: [512, 512]
batch_size: 32

gpus: 1,2,3,4
lr: 0.001
wd: 0.0005
momentum: 0.9
gpus: 0,1,2,3
epoch: 10
amp: False

network: 'resnet18_v1'
layers: ['stage4_activation1']

save_prefix: '~/gluon_detector/output'
