
model: 'centernet'
backbone: 'resnet18_v1'

dataset: 'coco'
train_split: 'train2017'
val_split: 'val2017'
num_classes: 80
input_size: 512
gpu_batch_size: 1

gpus: 0,1,2,3
lr: 0.003
wd: 0.0005
momentum: 0.9
gpus: 0,1,2,3
epoch: 10
optimizer: 'sgd'
amp: False

save_prefix: '~/gluon_detector/output'
save_frequent: 1
