model: 'retinanet'
backbone: 'resnet50_v1'
dataset: 'coco'
train_split: 'train2017'
val_split: 'val2017'
max_size: 1024
resize_shorter: 640
gpu_batch_size: 2
optimizer: 'sgd'
resume_epoch: 0
lr: 0.0003
wd: 0.0001
gpus: 0,1,2,3
use_amp: False
save_frequent: 1
save_prefix: '~/gluon_detector/output'
