
model: 'retinanet'

dataset: 'coco'
train_split: 'train2017'
val_split: 'val2017'

input_shape: [512, 512]
batch_size: 16

optimizer: 'sgd'
lr: 0.001
wd: 0.0005
momentum: 0.9
gpus: 0,1,2,3
epoch: 100
use_amp: False
save_frequent: 2

network: 'resnet50_v1'
layers: ['stage2_activation3', 'stage3_activation5', 'stage4_activation2']

save_prefix: '~/gluon_detector/output'
